### ISSUE TITLE
Potential Security Issue in Firefox

### ISSUE THREAD

**Issue by chillmetin** [hybtli/Portfolio-Website#1]
![image](https://user-images.githubusercontent.com/73022312/231049688-8bbf612f-30c0-4864-b131-e1e5fc72c3ef.png)

happens when opening the website

**Comment by chillmetin** [comment]
Still, does not work:
![image](https://user-images.githubusercontent.com/73022312/231868624-f1a38660-645e-4cfa-8b4f-18676028e0db.png)
![image](https://user-images.githubusercontent.com/73022312/231868682-6de7b25f-33f0-4001-9f40-5f3713fedd2f.png)

**Comment by hybtli** [comment]
It was re-tested on Brave and Firefox web browsers and it is still working without a security problem. Several issues can cause this problem on your browser. 

-  Probably, you have stricter security than general
-  You maybe have an antivirus which is blocking access to the website.
-  There can be installed any proxy server or VPN that prevents access.

Here, you can see [solution](https://aboutssl.org/how-to-fix-mozilla-pkix-self-signed-cert-error/) advice on how to fix your problem.
